# Generated by Django 5.0.1 on 2024-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_email_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("front", models.CharField(max_length=500)),
                ("back", models.CharField(max_length=500)),
                ("pronunciation", models.CharField(max_length=500)),
                ("is_favorite", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "words",
            },
        ),
    ]
