# Generated by Django 5.0.1 on 2024-04-24 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
