# Generated by Django 5.0.1 on 2024-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_word_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="back",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="front",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="pronunciation",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
