# Generated by Django 5.0.1 on 2024-04-27 05:41

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_full_name_alter_word_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="back",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="word",
            name="front",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="word",
            name="pronunciation",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("front", "back", "pronunciation", "user")},
        ),
        migrations.CreateModel(
            name="CustomToken",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Key",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=users.models.get_default_time, editable=False
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "db_table": "custom_tokens",
            },
        ),
    ]
